---
title: "Household Economy"
author: "coop711"
date: "2015년 10월 27일"
output: html_document
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(width = 180)
```

## Data

```{r, library}
library(xlsx)
library(knitr)
```

```{r, Data}
hh.econ.10th <- read.xlsx("../data/20151102192605.xlsx", 1, startRow = 5, endRow = 18, colIndex = 3:32, header = FALSE)
str(hh.econ.10th)
kable(hh.econ.10th[, 1:15])
kable(hh.econ.10th[, 16:30])
kable(rownames(hh.econ.10th) <- c(2003:2014, "15.14", "15.24"))
kable(colnames(hh.econ.10th) <- paste(rep(1:10, each = 3), c("분위.소득", "분위.소비지출", "분위.처분가능소득"), sep=""))
str(hh.econ.10th)
hh.econ.10th.11 <- matrix(as.numeric(hh.econ.10th["2011", ]), nrow = 3)
str(hh.econ.10th.11)
kable(hh.econ.10th.11, row.names = FALSE, col.names = paste(1:10, "분위"), caption = "소득 분위별 가계수지(2011년)")
dimnames(hh.econ.10th.11) <- list(c("소득", "소비지출", "처분가능소득"), paste(1:10, "분위", sep = ""))
kable(hh.econ.10th.11, caption = "소득 분위별 가계수지(2011년)")
kable(hh.econ.10th.11.2 <- hh.econ.10th.11[c(1, 3, 2), ])
```

## Save

```{r, save}
save.image("./hh_econ_10th.RData")
```


